spring:
  application:
    name: spring-jwt-security

  datasource:
    url: jdbc:mysql://localhost:3306/jwt_db
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# JWT authentication
security:
  jwt:
    secret-key: fdf06b39b64bead183bcb160098e01c455c2ffab38bc51d5c232d60e1c1f1022
    expiration-time: 60000

server:
  port: 8090

